name: Build

on: push

jobs:

  compile:
    name: Compile Project
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
      - name: Maven Compile
        run: mvn -B clean compile